stages:

  download_data:
    cmd: python src/data/download_data.py
    params:
    - kaggle_competition
    outs:
    - data/raw/sample_submission.csv:
        cache: false
    - data/raw/test.csv:
        cache: false
    - data/raw/train.csv:
        cache: false

  pca:
    cmd: python src/data/pca.py
    params:
      - n_components
    deps:
      - data/raw/train.csv
    outs:
      - data/interim/train_pca.csv

  lgbm_modelling:
    cmd: python src/model/lgbm.py
    deps:
      - data/interim/train_pca.csv
    outs:
      - models/lgbm/model.txt

#  lgbm_inference:
#    cmd: python src/inference/lgbm_inf.py
#    deps:
#      - models/lgbm/model.txt
#      - data/raw/test.csv
#    outs:
#      - data/submission/submission.csv

# You may submit a maximum of 5 entries per day.
#  submission:
#    cmd: kaggle competitions submit
#      tabular-playground-series-jan-2021
#      -f data/submission/submission.csv
#      -m "LightGBM"
