stages:

  download_data:
    cmd: python src/data/download_data.py
    params:
    - kaggle_competition
    outs:
    - data/raw/sample_submission.csv:
        cache: false
    - data/raw/test.csv:
        cache: false
    - data/raw/train.csv:
        cache: false

  scale:
    cmd: python src/data/scale.py -f data/raw/train.csv
    params:
      - features
    deps:
      - data/raw/train.csv
    outs:
      - data/interim/train_scaled.csv:
          cache: false

  lgbm_modelling:
    cmd: python src/model/lgbm.py
    deps:
      - data/interim/train_scaled.csv
    outs:
      - models/lgbm/model.txt

  scale_test:
    cmd: python src/data/scale.py -f data/raw/test.csv
    params:
      - features
    deps:
      - data/raw/test.csv
    outs:
      - data/interim/test_scaled.csv:
          cache: false

  lgbm_inference:
    cmd: python src/inference/lgbm_inf.py
    deps:
      - models/lgbm/model.txt
      - data/interim/test_scaled.csv
    outs:
      - data/submission/submission.csv

# You may submit a maximum of 5 entries per day.
  submission:
    cmd: kaggle competitions submit
      tabular-playground-series-jan-2021
      -f data/submission/submission.csv
      -m "LightGBM"
