stages:

  download_data:
    cmd: python src/data/download_data.py
    params:
    - kaggle_competition
    outs:
    - data/raw/sample_submission.csv:
        cache: false
    - data/raw/test.csv:
        cache: false
    - data/raw/train.csv:
        cache: false

  train_drop_outliers:
    cmd: python src/data/drop_outliers.py -f data/raw/train.csv
    deps:
      - data/raw/train.csv
    outs:
      - data/interim/train_cleaned.csv:
          cache: false

  gmr_fit_predict:
    cmd: python src/model/gmregr.py
    params:
      - features
    deps:
      - data/interim/train_cleaned.csv
      - data/interim/test_cleaned.csv
    outs:
      - data/submission/submission.csv

# You may submit a maximum of 5 entries per day.
#  submission:
#    cmd: kaggle competitions submit
#      tabular-playground-series-jan-2021
#      -f data/submission/submission.csv
#      -m "LightGBM"
