stages:

  download_data:
    cmd: python src/data/download_data.py
    params:
    - kaggle_competition
    outs:
    - data/raw/sample_submission.csv:
        cache: false
    - data/raw/test.csv:
        cache: false
    - data/raw/train.csv:
        cache: false

  lgbm_modelling:
    cmd: python src/model/lgbm.py
    deps:
      - data/raw/train.csv
    outs:
      - models/lgbm/model.txt
