kaggle_competition: 'tabular-playground-series-jan-2021'

features_to_logarithm:
  - "cont6"
  - "cont8"
  - "cont13"

features_to_div:
  - 'cont1'
  - 'cont2'
  - 'cont3'
  - 'cont4'
  - 'cont5'
#  - 'cont6'
  - 'cont6_logarithm'
  - 'cont7'
#  - 'cont8'
  - 'cont8_logarithm'
  - 'cont9'
  - 'cont10'
  - 'cont11'
  - 'cont12'
#  - 'cont13'
  - 'cont13_logarithm'
  - 'cont14'

features:
  - 'cont3'
  - 'cont2'
  - 'cont13_logarithm'
  - 'cont4'
  - 'cont7'
  - 'cont14'
  - 'cont1'
  - 'cont10'
  - 'cont4_div_cont11'
  - 'cont12'
  - 'cont11'
  - 'cont12_div_cont13_logarithm'
  - 'cont5'
  - 'cont6_logarithm'
  - 'cont9'
  - 'cont8_logarithm'
  - 'cont13_logarithm_div_cont4'
  - 'cont4_div_cont12'
  - 'cont11_div_cont13_logarithm'
  - 'cont13_logarithm_div_cont10'
  - 'cont2_div_cont1'
  - 'cont1_div_cont6_logarithm'
  - 'cont2_div_cont13_logarithm'
  - 'cont13_logarithm_div_cont11'
  - 'cont13_logarithm_div_cont6_logarithm'
  - 'cont10_div_cont13_logarithm'
  - 'cont1_div_cont12'
  - 'cont14_div_cont13_logarithm'
  - 'cont4_div_cont13_logarithm'
